In [1]:
import numpy as np
from scipy import sparse
from tools.luDecomposition import lu_decomposition
from tools.inverseMatrix import inverse_matrix
from tools.linearEquationsSystemSolve import linear_equations_system_solve
from tools.seidel import seidel

In [2]:
def lu_operations(a: sparse.csr_matrix):
    l, u, iteration_count_decomposition = lu_decomposition(a)
    inverse_a, iteration_count_inversion = inverse_matrix(a)

    print("A:")
    print(a.toarray())

    print("L:")
    print(l.toarray())

    print("U:")
    print(u.toarray())

    print("L * U:")
    print(l.dot(u).toarray())

    print("Iteration number")
    print(iteration_count_decomposition)
    print(">-----------------------------------------<")

    print("Inverse A:")
    print(inverse_a.toarray())

    print("(Inverse A) * A:")
    print(inverse_a.dot(a).toarray())

    print("Iteration number")
    print(iteration_count_inversion)
    print(">-----------------------------------------<")

    '''b = sparse.csr_matrix([[1.], [2.], [3.]])
    answer, iteration_count = linear_equations_system_solve(a, b)
    print("Solution of system A with B vector [1, 2, 3] (lu method)")
    print(answer.transpose().toarray())

    print("Iteration number")
    print(iteration_count)
    print(">-----------------------------------------<")'''

    b = np.array([1., 2., 3.])
    answer, iteration_count = seidel(a, b, 0.000001)
    print("Solution of system A with B vector [1, 2, 3] (Seidel method)")
    print(answer)
    print("Iteration number")
    print(iteration_count)
    print(">-----------------------------------------<")

In [3]:
lu_operations(sparse.csr_matrix([[10., -3., 5.], [-7., 6., -1.], [0., 2., 5.]]))

A:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
L:
[[ 1.          0.          0.        ]
 [-0.7         1.          0.        ]
 [ 0.          0.51282051  1.        ]]
U:
[[10.         -3.          5.        ]
 [ 0.          3.9         2.5       ]
 [ 0.          0.          3.71794872]]
L * U:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
Iteration number
23
>-----------------------------------------<
Inverse A:
[[ 0.19661892 -1.37844941  0.73134016]
 [-1.40466245 -2.7109868   0.61225091]
 [-5.58547382  4.12357038 -0.45001982]]
(Inverse A) * A:
[[ 11.61533509  -7.39787289   6.01824484]
 [  4.9302831  -10.82743164  -1.25107092]
 [-84.71973085  40.5978041  -34.30103855]]
Iteration number
93
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (lu method)
[[0.17367633 0.9262785  1.11871217]]
Iteration number
31
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (Seidel method)
[0.00689702 0.41379359 0.43448257]
I

In [4]:
lu_operations(sparse.csr_matrix([[20., 0., 5.], [-7., 3., -1.], [10., 2., -4.]]))

A:
[[20.  0.  5.]
 [-7.  3. -1.]
 [10.  2. -4.]]
L:
[[ 1.          0.          0.        ]
 [-0.35        1.          0.        ]
 [ 0.5         0.66666667  1.        ]]
U:
[[20.    0.    5.  ]
 [ 0.    3.    0.75]
 [ 0.    0.   -7.  ]]
L * U:
[[20.  0.  5.]
 [-7.  3. -1.]
 [10.  2. -4.]]
Iteration number
23
>-----------------------------------------<
Inverse A:
[[ 0.15407225 -0.05448221  0.07842004]
 [ 0.04251884  0.74966772  0.19670718]
 [-0.28701135  0.2501613  -0.2538578 ]]
(Inverse A) * A:
[[ 4.24702090e+00 -6.60655316e-03  5.11163295e-01]
 [-2.43022555e+00  2.64241753e+00 -1.32390224e+00]
 [-1.00299341e+01  2.42768290e-01 -6.69786841e-01]]
Iteration number
93
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (lu method)
[[0.56668994 1.70335761 0.59637488]]
Iteration number
31
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (Seidel method)
[ 0.08333323  0.81666656 -0.13333365]
Iteration number
135
>---

In [5]:
lu_operations(sparse.csr_matrix([[6., -3., 3.], [2., 2., -8.], [1., -2., 9.]]))


A:
[[ 6. -3.  3.]
 [ 2.  2. -8.]
 [ 1. -2.  9.]]
L:
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.16666667 -0.5         1.        ]]
U:
[[ 6. -3.  3.]
 [ 0.  3. -9.]
 [ 0.  0.  4.]]
L * U:
[[ 6. -3.  3.]
 [ 2.  2. -8.]
 [ 1. -2.  9.]]
Iteration number
23
>-----------------------------------------<
Inverse A:
[[-4.95458270e+00  1.21352866e+02 -1.44536394e+03]
 [-1.29316113e+01 -1.75132750e+03  4.92654653e+03]
 [-1.42324736e+00 -3.26250434e+03  9.31148795e+03]]
(Inverse A) * A:
[[ -1232.38570774   3148.2973646  -13993.96215684]
 [  1346.30185732 -13316.9532449   58310.74401591]
 [  2777.93979193 -25143.71484517 109899.15656135]]
Iteration number
93
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (lu method)
[[-1.32478892e+08 -6.32257838e+08 -4.32889442e+08]]
Iteration number
31
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (Seidel method)
[1.36111078 3.30555483 0.91666