In [13]:
import numpy as np
from scipy import sparse
from tools.luDecomposition import lu_decomposition
from tools.inverseMatrix import inverse_matrix
from tools.linearEquationsSystemSolve import linear_equations_system_solve
from tools.seidel import seidel

ImportError: cannot import name 'linear_equations_system_solve' from 'tools.linearEquationsSystemSolve' (E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\linearEquationsSystemSolve.py)

In [ ]:
def lu_operations(a: sparse.csr_matrix, b: np.array):
    l, u, iteration_count_decomposition = lu_decomposition(a)
    inverse_a, iteration_count_inversion = inverse_matrix(a)

    print("A:")
    print(a.toarray())

    print("L:")
    print(l.toarray())

    print("U:")
    print(u.toarray())

    print("L * U:")
    print(l.dot(u).toarray())

    print("Iteration number")
    print(iteration_count_decomposition)
    print(">-----------------------------------------<")

    print("Inverse A:")
    print(inverse_a.toarray())

    print("(Inverse A) * A:")
    print(inverse_a.dot(a).toarray())

    print("Iteration number")
    print(iteration_count_inversion)
    print(">-----------------------------------------<")

    answer, iteration_count = linear_equations_system_solve(a, b)
    print("Solution of system A with B vector (lu method)")
    print(answer.transpose().toarray())

    print("Iteration number")
    print(iteration_count)
    print(">-----------------------------------------<")

    answer, iteration_count = seidel(a, b, 0.000001)
    print("Solution of system A with B vector (Seidel method)")
    print(answer)
    print("Iteration number")
    print(iteration_count)
    print(">-----------------------------------------<")

In [15]:
lu_operations(sparse.csr_matrix([[10., -3., 5.], [-7., 6., -1.], [0., 2., 5.]]), np.array([1., 2., 3.]))

A:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
L:
[[ 1.          0.          0.        ]
 [-0.7         1.          0.        ]
 [ 0.          0.51282051  1.        ]]
U:
[[10.         -3.          5.        ]
 [ 0.          3.9         2.5       ]
 [ 0.          0.          3.71794872]]
L * U:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
Iteration number
23
>-----------------------------------------<
Inverse A:
[[ 0.22068966  0.17241379 -0.1862069 ]
 [ 0.24137931  0.34482759 -0.17241379]
 [-0.09655172 -0.13793103  0.26896552]]
(Inverse A) * A:
[[ 1.00000000e+00 -1.11022302e-16  2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Iteration number
59
>-----------------------------------------<
Solution of system A with B vector [1, 2, 3] (Seidel method)
[0.00689702 0.41379359 0.43448257]
Iteration number
54
>-----------------------------------------<


In [14]:
lu_operations(sparse.csr_matrix([[20., 0., 5., 4.], [-7., 3., -1., 9], [10., 2., -4., 2], [2., 9., 11., 55.]])
              ,np.array([1., 2., 3., 4.]))

A:
[[20.  0.  5.  4.]
 [-7.  3. -1.  9.]
 [10.  2. -4.  2.]
 [ 2.  9. 11. 55.]]
L:
[[ 1.          0.          0.          0.        ]
 [-0.35        1.          0.          0.        ]
 [ 0.5         0.66666667  1.          0.        ]
 [ 0.1         3.         -1.17857143  1.        ]]
U:
[[20.          0.          5.          4.        ]
 [ 0.          3.          0.75       10.4       ]
 [ 0.          0.         -7.         -6.93333333]
 [ 0.          0.          0.         15.22857143]]
L * U:
[[20.  0.  5.  4.]
 [-7.  3. -1.  9.]
 [10.  2. -4.  2.]
 [ 2.  9. 11. 55.]]
Iteration number
49
>-----------------------------------------<
Inverse A:
[[ 0.01751094 -0.03564728  0.03939962  0.00312695]
 [ 0.51626016  1.1097561  -0.21341463 -0.21138211]
 [ 0.23577236  0.34146341 -0.2195122  -0.06504065]
 [-0.13227017 -0.24859287  0.07739212  0.06566604]]
(Inverse A) * A:
[[ 1.00000000e+00  2.42861287e-17  6.93889390e-18  2.77555756e-17]
 [-3.49720253e-15  1.00000000e+00 -4.44089210e-16  0.000

In [ ]:
lu_operations(sparse.csr_matrix([[20., 0., 5., 4., 7.], [-7., 3., -1., 9., 9.],
                                 [10., 2., -4., 2, 2.], [2., 9., 11., 55., 5.], [7., 9., 6., 9., 5.]]),
              np.array([1., 2., 3., 4., 5.]))

A:
[[20.  0.  5.  4.  7.]
 [-7.  3. -1.  9.  9.]
 [10.  2. -4.  2.  2.]
 [ 2.  9. 11. 55.  5.]
 [ 7.  9.  6.  9.  5.]]
L:
[[ 1.          0.          0.          0.          0.        ]
 [-0.35        1.          0.          0.          0.        ]
 [ 0.5         0.66666667  1.          0.          0.        ]
 [ 0.1         3.         -1.17857143  1.          0.        ]
 [ 0.35        3.         -0.28571429 -1.67979987  1.        ]]
U:
[[  20.            0.            5.            4.            7.        ]
 [   0.            3.            0.75         10.4          11.45      ]
 [   0.            0.           -7.           -6.93333333   -9.13333333]
 [   0.            0.            0.           15.22857143  -40.81428571]
 [   0.            0.            0.            0.         -102.96935585]]
L * U:
[[20.  0.  5.  4.  7.]
 [-7.  3. -1.  9.  9.]
 [10.  2. -4.  2.  2.]
 [ 2.  9. 11. 55.  5.]
 [ 7.  9.  6.  9.  5.]]
Iteration number
89
>-----------------------------------------<
Invers

E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:19: RuntimeWarning: overflow encountered in double_scalars
  converge = np.sqrt(sum((x_new[i] - x[i]) ** 2 for i in range(n))) <= eps
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:14: RuntimeWarning: overflow encountered in double_scalars
  s1 = sum(a[i, j] * x_new[j] for j in range(i))
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:14: RuntimeWarning: invalid value encountered in double_scalars
  s1 = sum(a[i, j] * x_new[j] for j in range(i))
