In [22]:
import numpy as np
from scipy import sparse
from tools.luDecomposition import lu_decomposition
from tools.inverseMatrix import inverse_matrix
from tools.linearEquationsSystemSolve import linear_equations_system_solve
from tools.seidel import seidel

In [23]:
def lu_operations(a: sparse.csr_matrix):
    l, u = lu_decomposition(a)
    inverse_a = inverse_matrix(a)

    print("A:")
    print(a.toarray())

    print("L:")
    print(l.toarray())

    print("U:")
    print(u.toarray())

    print("L * U:")
    print(l.dot(u).toarray())

    print("Inverse A:")
    print(inverse_a.toarray())

    print("(Inverse A) * A:")
    print(inverse_a.dot(a).toarray())

    b = sparse.csr_matrix([[1.], [2.], [3.]])
    print("Solution of system A with B vector [1, 2, 3] (lu method)")
    print(linear_equations_system_solve(a, b).transpose().toarray())

    b = np.array([1., 2., 3.])
    print("Solution of system A with B vector [1, 2, 3] (Seidel method)")
    print(seidel(a, b, 0.000001))

In [24]:
print("Подходящая матрица #1")
lu_operations(sparse.csr_matrix([[10., -3., 5.], [-7., 6., -1.], [0., 2., 5.]]))

Подходящая матрица #1
A:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
L:
[[ 1.          0.          0.        ]
 [-0.7         1.          0.        ]
 [ 0.          0.51282051  1.        ]]
U:
[[10.         -3.          5.        ]
 [ 0.          3.9         2.5       ]
 [ 0.          0.          3.71794872]]
L * U:
[[10. -3.  5.]
 [-7.  6. -1.]
 [ 0.  2.  5.]]
Inverse A:
[[ 0.22068966  0.17241379 -0.1862069 ]
 [ 0.24137931  0.34482759 -0.17241379]
 [-0.09655172 -0.13793103  0.26896552]]
(Inverse A) * A:
[[ 1.00000000e+00 -1.11022302e-16  2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Solution of system A with B vector [1, 2, 3] (lu method)
[[0.00689655 0.4137931  0.43448276]]
Solution of system A with B vector [1, 2, 3] (Seidel method)
[0.00689702 0.41379359 0.43448257]


In [25]:
print("Подходящая матрица #2")
lu_operations(sparse.csr_matrix([[20., 0., 5.], [-7., 3., -1.], [10., 2., -4.]]))

Подходящая матрица #2
A:
[[20.  0.  5.]
 [-7.  3. -1.]
 [10.  2. -4.]]
L:
[[ 1.          0.          0.        ]
 [-0.35        1.          0.        ]
 [ 0.5         0.66666667  1.        ]]
U:
[[20.    0.    5.  ]
 [ 0.    3.    0.75]
 [ 0.    0.   -7.  ]]
L * U:
[[20.  0.  5.]
 [-7.  3. -1.]
 [10.  2. -4.]]
Inverse A:
[[ 0.02380952 -0.02380952  0.03571429]
 [ 0.09047619  0.30952381  0.03571429]
 [ 0.1047619   0.0952381  -0.14285714]]
(Inverse A) * A:
[[ 1.00000000e+00  0.00000000e+00  2.77555756e-17]
 [-3.33066907e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Solution of system A with B vector [1, 2, 3] (lu method)
[[ 0.08333333  0.81666667 -0.13333333]]
Solution of system A with B vector [1, 2, 3] (Seidel method)
[ 0.08333323  0.81666656 -0.13333365]


In [26]:
print("Подходящая матрица #3")
lu_operations(sparse.csr_matrix([[6., -3., 3.], [2., 2., -8.], [1., -2., 9.]]))

Подходящая матрица #3
A:
[[ 6. -3.  3.]
 [ 2.  2. -8.]
 [ 1. -2.  9.]]
L:
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.16666667 -0.5         1.        ]]
U:
[[ 6. -3.  3.]
 [ 0.  3. -9.]
 [ 0.  0.  4.]]
L * U:
[[ 6. -3.  3.]
 [ 2.  2. -8.]
 [ 1. -2.  9.]]
Inverse A:
[[ 0.02777778  0.29166667  0.25      ]
 [-0.36111111  0.70833333  0.75      ]
 [-0.08333333  0.125       0.25      ]]
(Inverse A) * A:
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Solution of system A with B vector [1, 2, 3] (lu method)
[[1.36111111 3.30555556 0.91666667]]
Solution of system A with B vector [1, 2, 3] (Seidel method)
[1.36111078 3.30555483 0.91666654]


In [27]:
print("Неподходящая матрица #1")
lu_operations(sparse.csr_matrix([[1., 1., 1.], [2., 2., 2.], [3., 3., 3.]]))


Неподходящая матрица #1
A:
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
L:
[[ 1.  0.  0.]
 [ 2. nan  0.]
 [ 3. nan nan]]
U:
[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0. nan nan]]
L * U:
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3. nan nan]]
Inverse A:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
(Inverse A) * A:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Solution of system A with B vector [1, 2, 3] (lu method)
[[nan nan nan]]
Solution of system A with B vector [1, 2, 3] (Seidel method)
[1. 0. 0.]


E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\luDecomposition.py:27: RuntimeWarning: invalid value encountered in double_scalars
  l[j, i] = u[j, i] / u[i, i]
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\venv\lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:206: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)


In [ ]:
print("Неподходящая матрица #2")
lu_operations(sparse.csr_matrix([[1., 1., 1.], [5., 2., 5.], [0., 0., 0.]]))


Неподходящая матрица #2
A:
[[1. 1. 1.]
 [5. 2. 5.]
 [0. 0. 0.]]
L:
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [ 0.  0. nan]]
U:
[[ 1.  1.  1.]
 [ 0. -3.  0.]
 [ 0.  0.  0.]]
L * U:
[[1. 1. 1.]
 [5. 2. 5.]
 [0. 0. 0.]]
Inverse A:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
(Inverse A) * A:
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Solution of system A with B vector [1, 2, 3] (lu method)
[[nan nan nan]]
Solution of system A with B vector [1, 2, 3] (Seidel method)


E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\luDecomposition.py:22: RuntimeWarning: invalid value encountered in double_scalars
  l[j, i] = u[j, i] / u[i, i]
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  x_new[i] = (b[i] - s1 - s2) / a[i, i]
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:15: RuntimeWarning: invalid value encountered in double_scalars
  x_new[i] = (b[i] - s1 - s2) / a[i, i]
E:\ITMO prog\Prog\Py\ITMO_AppliedMath\Lab3\tools\seidel.py:13: RuntimeWarning: invalid value encountered in double_scalars
  s1 = sum(a[i, j] * x_new[j] for j in range(i))
